//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.26 at 09:23:25 AM CEST 
//


package org.tes.hkx.lib;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hkpackfileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hkpackfileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hksection" type="{}hksectionType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="classversion" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="contentsversion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="toplevelobject" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hkpackfileType", propOrder = {
    "hksection"
})
public class HkpackfileType {

    @XmlElement(required = true)
    protected HksectionType hksection;
    @XmlAttribute(name = "classversion")
    protected Byte classversion;
    @XmlAttribute(name = "contentsversion")
    protected String contentsversion;
    @XmlAttribute(name = "toplevelobject")
    protected String toplevelobject;

    /**
     * Gets the value of the hksection property.
     * 
     * @return
     *     possible object is
     *     {@link HksectionType }
     *     
     */
    public HksectionType getHksection() {
        return hksection;
    }

    /**
     * Sets the value of the hksection property.
     * 
     * @param value
     *     allowed object is
     *     {@link HksectionType }
     *     
     */
    public void setHksection(HksectionType value) {
        this.hksection = value;
    }

    /**
     * Gets the value of the classversion property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getClassversion() {
        return classversion;
    }

    /**
     * Sets the value of the classversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setClassversion(Byte value) {
        this.classversion = value;
    }

    /**
     * Gets the value of the contentsversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentsversion() {
        return contentsversion;
    }

    /**
     * Sets the value of the contentsversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentsversion(String value) {
        this.contentsversion = value;
    }

    /**
     * Gets the value of the toplevelobject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToplevelobject() {
        return toplevelobject;
    }

    /**
     * Sets the value of the toplevelobject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToplevelobject(String value) {
        this.toplevelobject = value;
    }

}
