//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.26 at 09:23:25 AM CEST 
//


package org.tes.hkx.lib;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.tes.hkxlib package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Hkpackfile_QNAME = new QName("", "hkpackfile");
    private final static QName _HkparamTypeHkobject_QNAME = new QName("", "hkobject");
    private final static QName _HkparamTypeHkcstring_QNAME = new QName("", "hkcstring");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.tes.hkxlib
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HkpackfileType }
     * 
     */
    public HkpackfileType createHkpackfileType() {
        return new HkpackfileType();
    }

    /**
     * Create an instance of {@link HkobjectType }
     * 
     */
    public HkobjectType createHkobjectType() {
        return new HkobjectType();
    }

    /**
     * Create an instance of {@link HksectionType }
     * 
     */
    public HksectionType createHksectionType() {
        return new HksectionType();
    }

    /**
     * Create an instance of {@link HkparamType }
     * 
     */
    public HkparamType createHkparamType() {
        return new HkparamType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HkpackfileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hkpackfile")
    public JAXBElement<HkpackfileType> createHkpackfile(HkpackfileType value) {
        return new JAXBElement<HkpackfileType>(_Hkpackfile_QNAME, HkpackfileType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HkobjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hkobject", scope = HkparamType.class)
    public JAXBElement<HkobjectType> createHkparamTypeHkobject(HkobjectType value) {
        return new JAXBElement<HkobjectType>(_HkparamTypeHkobject_QNAME, HkobjectType.class, HkparamType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hkcstring", scope = HkparamType.class)
    public JAXBElement<String> createHkparamTypeHkcstring(String value) {
        return new JAXBElement<String>(_HkparamTypeHkcstring_QNAME, String.class, HkparamType.class, value);
    }

}
